import axios from 'axios'

const PROFILE_AUTH_API_PATH = '/api/v1/profile-auth'

function createElement(tagName, options = {}) {
  const element = document.createElement(tagName)

  if (options.className) {
    element.className = options.className
  }
  if (options.text) {
    element.textContent = options.text
  }

  return element
}

function requestProfileToken(serverUrl) {
  return new Promise((resolve) => {
    const overlay = createElement('div', { className: 'profile-auth' })
    const form = createElement('form', { className: 'profile-auth__form' })
    const title = createElement('h1', { text: 'Connect to Leon' })
    const description = createElement('p', {
      text: 'Enter the profile token generated by your Leon instance.'
    })
    const input = createElement('input')
    const button = createElement('button', { text: 'Connect' })
    const error = createElement('p', { className: 'profile-auth__error' })

    input.type = 'password'
    input.name = 'profile-token'
    input.placeholder = 'profile:token'
    input.autocomplete = 'current-password'
    input.required = true
    button.type = 'submit'

    form.append(title, description, input, button, error)
    overlay.append(form)
    document.body.append(overlay)
    input.focus()

    form.addEventListener('submit', async (event) => {
      event.preventDefault()
      button.disabled = true
      error.textContent = ''

      try {
        await axios.post(
          `${serverUrl}${PROFILE_AUTH_API_PATH}`,
          { token: input.value.trim() },
          { withCredentials: true }
        )
        overlay.remove()
        resolve()
      } catch (requestError) {
        error.textContent =
          requestError.response?.data?.message ||
          'Unable to authenticate this profile.'
        button.disabled = false
        input.select()
      }
    })
  })
}

/** Ensure the browser has a profile cookie before initializing the Leon app. */
export async function ensureProfileAuthentication(serverUrl) {
  axios.defaults.withCredentials = true
  const response = await axios.get(`${serverUrl}${PROFILE_AUTH_API_PATH}`)

  if (!response.data.authenticated) {
    await requestProfileToken(serverUrl)
  }
}
