def get_all():
    return [
        '1C Enterprise',
        'ABAP',
        'ABNF',
        'ActionScript',
        'Ada',
        'Adobe Font Metrics',
        'Agda',
        'AGS Script',
        'Alloy',
        'Alpine Abuild',
        'AMPL',
        'AngelScript',
        'Ant Build System',
        'ANTLR',
        'ApacheConf',
        'Apex',
        'API Blueprint',
        'APL',
        'Apollo Guidance Computer',
        'AppleScript',
        'Arc',
        'AsciiDoc',
        'ASN.1',
        'ASP',
        'AspectJ',
        'Assembly',
        'Asymptote',
        'ATS',
        'Augeas',
        'AutoHotkey',
        'AutoIt',
        'Awk',
        'Ballerina',
        'Batchfile',
        'Befunge',
        'Bison',
        'BitBake',
        'Blade',
        'BlitzBasic',
        'BlitzMax',
        'Bluespec',
        'Boo',
        'Brainfuck',
        'Brightscript',
        'Bro',
        'C',
        'C#',
        'C++',
        'C-ObjDump',
        'C2hs Haskell',
        "Cap'n Proto", 'CartoCSS',
        'Ceylon',
        'Chapel',
        'Charity',
        'ChucK',
        'Cirru',
        'Clarion',
        'Clean',
        'Click',
        'CLIPS',
        'Clojure',
        'Closure Templates',
        'Cloud Firestore Security Rules',
        'CMake',
        'COBOL',
        'CoffeeScript',
        'ColdFusion',
        'ColdFusion CFC',
        'COLLADA',
        'Common Lisp',
        'Common Workflow Language',
        'Component Pascal',
        'CoNLL-U',
        'Cool',
        'Coq',
        'Cpp-ObjDump',
        'Creole',
        'Crystal',
        'CSON',
        'Csound',
        'Csound Document',
        'Csound Score',
        'CSS',
        'CSV',
        'Cuda',
        'CWeb',
        'Cycript',
        'Cython',
        'D',
        'D-ObjDump',
        'Darcs Patch',
        'Dart',
        'DataWeave',
        'desktop',
        'Diff',
        'DIGITAL Command Language',
        'DM',
        'DNS Zone',
        'Dockerfile',
        'Dogescript',
        'DTrace',
        'Dylan',
        'E',
        'Eagle',
        'Easybuild',
        'EBNF',
        'eC',
        'Ecere Projects',
        'ECL',
        'ECLiPSe',
        'Edje Data Collection',
        'edn',
        'Eiffel',
        'EJS',
        'Elixir',
        'Elm',
        'Emacs Lisp',
        'EmberScript',
        'EML',
        'EQ',
        'Erlang',
        'F#',
        'F*',
        'Factor',
        'Fancy',
        'Fantom',
        'FIGlet Font',
        'Filebench WML',
        'Filterscript',
        'fish',
        'FLUX',
        'Formatted',
        'Forth',
        'Fortran',
        'FreeMarker',
        'Frege',
        'G-code',
        'Game Maker Language',
        'GAMS',
        'GAP',
        'GCC Machine Description',
        'GDB',
        'GDScript',
        'Genie',
        'Genshi',
        'Gentoo Ebuild',
        'Gentoo Eclass',
        'Gerber Image',
        'Gettext Catalog',
        'Gherkin',
        'GLSL',
        'Glyph',
        'Glyph Bitmap Distribution Format',
        'GN',
        'Gnuplot',
        'Go',
        'Golo',
        'Gosu',
        'Grace',
        'Gradle',
        'Grammatical Framework',
        'Graph Modeling Language',
        'GraphQL',
        'Graphviz (DOT)',
        'Groovy',
        'Groovy HttpServer Pages',
        'Hack',
        'Haml',
        'Handlebars',
        'HAProxy',
        'Harbour',
        'Haskell',
        'Haxe',
        'HCL',
        'HiveQL',
        'HLSL',
        'HTML',
        'HTML+Django',
        'HTML+ECR',
        'HTML+EEX',
        'HTML+ERB',
        'HTML+PHP',
        'HTML+Razor',
        'HTTP',
        'HXML',
        'Hy',
        'HyPhy',
        'IDL',
        'Idris',
        'IGOR Pro',
        'Inform 7',
        'INI',
        'Inno Setup',
        'Io',
        'Ioke',
        'IRC log',
        'Isabelle',
        'Isabelle ROOT',
        'J',
        'Jasmin',
        'Java',
        'Java Properties',
        'Java HttpServer Pages',
        'JavaScript',
        'JFlex',
        'Jison',
        'Jison Lex',
        'Jolie',
        'JSON',
        'JSON with Comments',
        'JSON5',
        'JSONiq',
        'JSONLD',
        'Jsonnet',
        'JSX',
        'Julia',
        'Jupyter Notebook',
        'KiCad Layout',
        'KiCad Legacy Layout',
        'KiCad Schematic',
        'Kit',
        'Kotlin',
        'KRL',
        'LabVIEW',
        'Lasso',
        'Latte',
        'Lean',
        'Less',
        'Lex',
        'LFE',
        'LilyPond',
        'Limbo',
        'Linker Script',
        'Linux Kernel Module',
        'Liquid',
        'Literate Agda',
        'Literate CoffeeScript',
        'Literate Haskell',
        'LiveScript',
        'LLVM',
        'Logos',
        'Logtalk',
        'LOLCODE',
        'LookML',
        'LoomScript',
        'LSL',
        'Lua',
        'M',
        'M4',
        'M4Sugar',
        'Makefile',
        'Mako',
        'Markdown',
        'Marko',
        'Mask',
        'Mathematica',
        'MATLAB',
        'Maven POM',
        'Max',
        'MAXScript',
        'mcfunction',
        'MediaWiki',
        'Mercury',
        'Meson',
        'Metal',
        'MiniD',
        'Mirah',
        'Modelica',
        'Modula-2',
        'Modula-3',
        'Module Management System',
        'Monkey',
        'Moocode',
        'MoonScript',
        'MQL4',
        'MQL5',
        'MTML',
        'MUF',
        'mupad',
        'Myghty',
        'NCL',
        'Nearley',
        'Nemerle',
        'nesC',
        'NetLinx',
        'NetLinx+ERB',
        'NetLogo',
        'NewLisp',
        'Nextflow',
        'Nginx',
        'Nim',
        'Ninja',
        'Nit',
        'Nix',
        'NL',
        'NSIS',
        'Nu',
        'NumPy',
        'ObjDump',
        'Objective-C',
        'Objective-C++',
        'Objective-J',
        'OCaml',
        'Omgrofl',
        'ooc',
        'Opa',
        'Opal',
        'OpenCL',
        'OpenEdge ABL',
        'OpenRC runscript',
        'OpenSCAD',
        'OpenType Feature File',
        'Org',
        'Ox',
        'Oxygene',
        'Oz',
        'P4',
        'Pan',
        'Papyrus',
        'Parrot',
        'Parrot Assembly',
        'Parrot Internal Representation',
        'Pascal',
        'Pawn',
        'Pep8',
        'Perl',
        'Perl 6',
        'PHP',
        'Pic',
        'Pickle',
        'PicoLisp',
        'PigLatin',
        'Pike',
        'PLpgSQL',
        'PLSQL',
        'Pod',
        'Pod 6',
        'PogoScript',
        'Pony',
        'PostCSS',
        'PostScript',
        'POV-Ray SDL',
        'PowerBuilder',
        'PowerShell',
        'Processing',
        'Prolog',
        'Propeller Spin',
        'Protocol Buffer',
        'Public Key',
        'Pug',
        'Puppet',
        'Pure Data',
        'PureBasic',
        'PureScript',
        'Python',
        'Python console',
        'Python traceback',
        'q',
        'QMake',
        'QML',
        'Quake',
        'R',
        'Racket',
        'Ragel',
        'RAML',
        'Rascal',
        'Raw token data',
        'RDoc',
        'REALbasic',
        'Reason',
        'Rebol',
        'Red',
        'Redcode',
        'Regular Expression',
        "Ren'Py", 'RenderScript',
        'reStructuredText',
        'REXX',
        'RHTML',
        'Rich Text Format',
        'Ring',
        'RMarkdown',
        'RobotFramework',
        'Roff',
        'Rouge',
        'RPC',
        'RPM Spec',
        'Ruby',
        'RUNOFF',
        'Rust',
        'Sage',
        'SaltStack',
        'SAS',
        'Sass',
        'Scala',
        'Scaml',
        'Scheme',
        'Scilab',
        'SCSS',
        'sed',
        'Self',
        'ShaderLab',
        'Shell',
        'ShellSession',
        'Shen',
        'Slash',
        'Slice',
        'Slim',
        'Smali',
        'Smalltalk',
        'Smarty',
        'SMT',
        'Solidity',
        'SourcePawn',
        'SPARQL',
        'Spline Font Database',
        'SQF',
        'SQL',
        'SQLPL',
        'Squirrel',
        'SRecode Template',
        'Stan',
        'Standard ML',
        'Stata',
        'STON',
        'Stylus',
        'SubRip Text',
        'SugarSS',
        'SuperCollider',
        'SVG',
        'Swift',
        'SystemVerilog',
        'Tcl',
        'Tcsh',
        'Tea',
        'Terra',
        'TeX',
        'Text',
        'Textile',
        'Thrift',
        'TI Program',
        'TLA',
        'TOML',
        'Turing',
        'Turtle',
        'Twig',
        'TXL',
        'Type Language',
        'TypeScript',
        'Unified Parallel C',
        'Unity3D Asset',
        'Unix Assembly',
        'Uno',
        'UnrealScript',
        'UrWeb',
        'Vala',
        'VCL',
        'Verilog',
        'VHDL',
        'Vim script',
        'Visual Basic',
        'Volt',
        'Vue',
        'Wavefront Material',
        'Wavefront Object',
        'wdl',
        'Web Ontology Language',
        'WebAssembly',
        'WebIDL',
        'Windows Registry Entries',
        'wisp',
        'World of Warcraft Addon Data',
        'X BitMap',
        'X Font Directory Index',
        'X PixMap',
        'X10',
        'xBase',
        'XC',
        'XCompose',
        'XML',
        'Xojo',
        'XPages',
        'XProc',
        'XQuery',
        'XS',
        'XSLT',
        'Xtend',
        'Yacc',
        'YAML',
        'YANG',
        'YARA',
        'YASnippet',
        'Zephir',
        'Zig',
        'Zimpl'
    ]
